version: '3.8'

services:
  app:
    build: .
    container_name: trading-bot
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
      - ./data/trades.json:/app/trades.json
    restart: unless-stopped



